language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - cp src/server/configs/_configs.js src/server/configs/configs.js
  - cp src/server/configs/_configs.providers.auth.js src/server/configs/configs.providers.auth.js